version: '3.8'
services:
  db:
    image: postgres
    # restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: file_storage
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql/:/docker-entrypoint-initdb.d
volumes:
  pgdata:
